name: sach_cua_t
description: "Quản lý sách cá nhân"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3+1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
