name: sach_cua_t
description: "Quản lý sách cá nhân"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  image_picker: ^1.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  webview_flutter: ^4.8.0
  man_hinh_ung_dung:
    path: ../../man_hinh_ung_dung

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sachcuat.db
    - assets/book.jpg
