name: sach_cua_t
description: "Quản lý sách cá nhân"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  image_picker: ^1.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  url_launcher: 6.3.2
  # if XCode < 14.3
  webview_flutter: 4.10.0
  webview_flutter_wkwebview: 3.17.0
  # else newer xcode
  # webview_flutter: 4.13.1
  # end if
  flutter_pdfview: 1.4.4
  man_hinh_ung_dung:
    path: ../libraries/man_hinh_ung_dung

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/sachcuat.db
    - assets/book.jpg
    - assets/gioi_thieu_vi.pdf
    - assets/tim_kiem_vi.pdf
    - assets/web_vi.pdf
    - assets/sach_vi.pdf
    - assets/mo_dau_vi.pdf
